create or replace function public.normalize_player_name(value text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select regexp_replace(btrim(value), '[[:space:]]+', ' ', 'g');
$$;

create or replace function public.calculate_ranked_score(
  difficulty smallint,
  duration_ms integer,
  mistakes smallint,
  hints_used smallint,
  move_count integer
)
returns bigint
language sql
immutable
strict
set search_path = ''
as $$
  select greatest(
    1::bigint,
    (array[1000000, 2000000, 3000000, 5000000, 8000000, 13000000]::bigint[])[difficulty]
      + greatest(0, 1000000 - duration_ms)
      + greatest(0, 3 - mistakes) * 25000
      + greatest(0, 500 - move_count) * 100
      - hints_used * 100000
  );
$$;

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_id uuid not null unique,
  player_name varchar(20) not null,
  score bigint not null,
  difficulty smallint not null default 1,
  duration_ms integer not null default 0,
  mistakes smallint not null default 0,
  move_count integer not null default 0,
  created_at timestamptz not null default now(),
  constraint scores_player_name_length check (char_length(public.normalize_player_name(player_name)) between 1 and 20),
  constraint scores_player_name_visible check (player_name = public.normalize_player_name(player_name) and player_name !~ '[[:cntrl:]]'),
  constraint scores_player_name_reserved check (lower(player_name) <> all (array['admin', 'administrator', 'moderator', 'system', 'supabase', '官方', '管理员'])),
  constraint scores_score_range check (score between 1 and 20000000)
);

alter table public.scores
  add column if not exists difficulty smallint not null default 1,
  add column if not exists duration_ms integer not null default 0,
  add column if not exists mistakes smallint not null default 0,
  add column if not exists move_count integer not null default 0;

alter table public.scores drop constraint if exists scores_player_name_length;
alter table public.scores drop constraint if exists scores_player_name_visible;
alter table public.scores drop constraint if exists scores_player_name_reserved;
alter table public.scores
  add constraint scores_player_name_length
    check (char_length(public.normalize_player_name(player_name)) between 1 and 20),
  add constraint scores_player_name_visible
    check (player_name = public.normalize_player_name(player_name) and player_name !~ '[[:cntrl:]]'),
  add constraint scores_player_name_reserved
    check (lower(player_name) <> all (array['admin', 'administrator', 'moderator', 'system', 'supabase', '官方', '管理员']));

create index if not exists scores_global_rank
  on public.scores (score desc, created_at asc, id asc);

create table if not exists public.score_submission_guards (
  player_id uuid primary key,
  window_started_at timestamptz not null default now(),
  attempts smallint not null default 0,
  last_submission_id uuid,
  last_response jsonb,
  updated_at timestamptz not null default now(),
  constraint score_submission_guard_attempts check (attempts between 0 and 10)
);

alter table public.scores enable row level security;
alter table public.scores force row level security;
alter table public.score_submission_guards enable row level security;
alter table public.score_submission_guards force row level security;

revoke all on table public.scores from public, anon, authenticated;
revoke all on table public.score_submission_guards from public, anon, authenticated;

drop policy if exists "Public scores are readable" on public.scores;

drop function if exists public.submit_score(uuid, text, bigint);

create or replace function public.submit_score(
  p_player_id uuid,
  p_player_name text,
  p_difficulty smallint,
  p_duration_ms integer,
  p_mistakes smallint,
  p_hints_used smallint,
  p_move_count integer,
  p_submission_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := public.normalize_player_name(p_player_name);
  minimum_duration_ms integer;
  computed_score bigint;
  stored_score public.scores%rowtype;
  guard public.score_submission_guards%rowtype;
  response jsonb;
  score_changed boolean := false;
begin
  if p_player_id is null or p_submission_id is null then
    raise exception using errcode = '22023', message = 'player_id and submission_id are required';
  end if;
  if normalized_name is null
      or char_length(normalized_name) not between 1 and 20
      or normalized_name ~ '[[:cntrl:]]'
      or lower(normalized_name) = any (array['admin', 'administrator', 'moderator', 'system', 'supabase', '官方', '管理员']) then
    raise exception using errcode = '22023', message = 'player_name must contain 1 to 20 visible characters';
  end if;
  if p_difficulty is null or p_difficulty not between 1 and 6 then
    raise exception using errcode = '22023', message = 'difficulty is outside the accepted range';
  end if;
  minimum_duration_ms := (array[5000, 10000, 15000, 20000, 30000, 60000]::integer[])[p_difficulty];
  if p_duration_ms is null or p_duration_ms < minimum_duration_ms or p_duration_ms > 86400000 then
    raise exception using errcode = '22023', message = 'duration is outside the plausible range';
  end if;
  if p_mistakes is null or p_mistakes not between 0 and 2 then
    raise exception using errcode = '22023', message = 'mistakes are outside the accepted range';
  end if;
  if p_hints_used is null or p_hints_used <> 0 then
    raise exception using errcode = '22023', message = 'ranked submissions cannot use hints';
  end if;
  if p_move_count is null or p_move_count not between 8 and 10000 then
    raise exception using errcode = '22023', message = 'move_count is outside the plausible range';
  end if;

  insert into public.score_submission_guards (player_id)
  values (p_player_id)
  on conflict (player_id) do nothing;

  select *
    into guard
    from public.score_submission_guards
    where player_id = p_player_id
    for update;

  if guard.last_submission_id = p_submission_id and guard.last_response is not null then
    return guard.last_response || jsonb_build_object('duplicate', true);
  end if;

  if guard.window_started_at <= now() - interval '1 minute' then
    guard.window_started_at := now();
    guard.attempts := 0;
  end if;
  if guard.attempts >= 10 then
    raise exception using errcode = 'P0001', message = 'submission rate limit exceeded';
  end if;

  computed_score := public.calculate_ranked_score(
    p_difficulty,
    p_duration_ms,
    p_mistakes,
    p_hints_used,
    p_move_count
  );

  insert into public.scores as current_score (
    player_id,
    player_name,
    score,
    difficulty,
    duration_ms,
    mistakes,
    move_count
  )
  values (
    p_player_id,
    normalized_name,
    computed_score,
    p_difficulty,
    p_duration_ms,
    p_mistakes,
    p_move_count
  )
  on conflict (player_id) do update
    set player_name = excluded.player_name,
        score = excluded.score,
        difficulty = excluded.difficulty,
        duration_ms = excluded.duration_ms,
        mistakes = excluded.mistakes,
        move_count = excluded.move_count,
        created_at = now()
    where excluded.score > current_score.score
  returning current_score.* into stored_score;

  score_changed := found;
  if not score_changed then
    select *
      into stored_score
      from public.scores
      where player_id = p_player_id;
  end if;

  response := jsonb_build_object(
    'updated', score_changed,
    'duplicate', false,
    'player_id', stored_score.player_id,
    'player_name', stored_score.player_name,
    'score', stored_score.score,
    'difficulty', stored_score.difficulty,
    'duration_ms', stored_score.duration_ms,
    'mistakes', stored_score.mistakes,
    'move_count', stored_score.move_count,
    'created_at', stored_score.created_at
  );

  update public.score_submission_guards
    set window_started_at = guard.window_started_at,
        attempts = guard.attempts + 1,
        last_submission_id = p_submission_id,
        last_response = response,
        updated_at = now()
    where player_id = p_player_id;

  return response;
end;
$$;

create or replace function public.get_leaderboard(
  p_player_id uuid default null
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with ranked as (
    select
      rank() over (order by score desc, created_at asc, id asc)::bigint as rank,
      player_id,
      player_name as display_name,
      score,
      created_at as submitted_at
    from public.scores
  ),
  top_rows as (
    select rank, display_name, score, submitted_at
    from ranked
    where rank <= 100
    order by rank
  ),
  self_row as (
    select rank, display_name, score, submitted_at
    from ranked
    where player_id = p_player_id
    limit 1
  )
  select jsonb_build_object(
    'entries',
    coalesce(
      (select jsonb_agg(to_jsonb(top_rows) order by rank) from top_rows),
      '[]'::jsonb
    ),
    'self_entry',
    coalesce(
      (select to_jsonb(self_row) from self_row),
      '{}'::jsonb
    )
  );
$$;

revoke all on function public.get_leaderboard(uuid) from public;
revoke all on function public.normalize_player_name(text) from public;
revoke all on function public.calculate_ranked_score(smallint, integer, smallint, smallint, integer) from public;
revoke all on function public.submit_score(uuid, text, smallint, integer, smallint, smallint, integer, uuid) from public;
grant execute on function public.submit_score(uuid, text, smallint, integer, smallint, smallint, integer, uuid) to anon, authenticated;
grant execute on function public.get_leaderboard(uuid) to anon, authenticated;

comment on table public.scores is
  'One public high-score row per locally generated anonymous player ID.';
comment on function public.submit_score(uuid, text, smallint, integer, smallint, smallint, integer, uuid) is
  'Validates ranked metrics, rate-limits and deduplicates submissions, computes the score server-side, and stores only improvements.';
comment on function public.get_leaderboard(uuid) is
  'Returns the global Top 100 plus the requested anonymous player position.';
